
package com.voyage.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PyWebServiceImplService", targetNamespace = "http://impl.webservice.voyage.com/", wsdlLocation = "http://localhost:12025/service/IPyWebService?wsdl")
public class PyWebServiceImplService
    extends Service
{

    private final static URL PYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.voyage.webservice.client.PyWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.voyage.webservice.client.PyWebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:12025/service/IPyWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:12025/service/IPyWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PyWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PyWebServiceImplService() {
        super(PYWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.webservice.voyage.com/", "PyWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns PyWebServiceImpl
     */
    @WebEndpoint(name = "PyWebServiceImplPort")
    public PyWebServiceImpl getPyWebServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.voyage.com/", "PyWebServiceImplPort"), PyWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PyWebServiceImpl
     */
    @WebEndpoint(name = "PyWebServiceImplPort")
    public PyWebServiceImpl getPyWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.voyage.com/", "PyWebServiceImplPort"), PyWebServiceImpl.class, features);
    }

}
